name: moviedb_seach
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  rxdart: ^0.16.6
  sqflite: ^2.0.0
  path_provider: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
     - family: NunitoSans
       fonts:
         - asset: assets/NunitoSans-Regular.ttf
     - family: Poppins
       fonts:
         - asset: assets/Poppins-Regular.ttf
